name: Cycle2U Backend Build

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore and build backend
      run: |
        dotnet restore ./backend/Cycle2U.csproj
        dotnet build ./backend/Cycle2U.csproj --configuration Release

    - name: Apply EF Core migration
      run: dotnet ef database update --project ./backend/Cycle2U.csproj

    - name: Publish backend
      run: dotnet publish ./backend/Cycle2U.csproj --configuration Release --output ./publish
    - name: Deploy to Render
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

