name: Build and Run with Docker Compose

on:
  push:
    branches:
      - master

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub (optional)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run containers with Docker Compose
        run: |
          docker-compose -f .github/workflows/docker-compose.yml up --build -d

      - name: Show running containers
        run: docker ps

      - name: Stop containers
        run: docker-compose -f .github/workflows/docker-compose.yml down
