name: Build and Run with Docker Compose

on:
  push:
    branches:
      - master

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore .NET dependencies
        run: |
          cd backend
          dotnet restore

      - name: Build and run containers with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Show running containers
        run: docker ps

      - name: Stop containers
        run: docker-compose -f docker-compose.yml down
