name: Cycle2U Frontend Build

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install production dependencies only
      run: |
        cd frontend
        npm install 
        npx next telemetry disable
        npm install react@18.2.0 react-dom@18.2.0
        npm install react-leaflet@4.2.1 leaflet@1.9.4
        npm install framer-motion motion
        npm install --save-dev typescript @types/react @types/node
        npm install @vercel/analytics

    - name: Build frontend
      run: |
        cd frontend
        npm run build