
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - cycle2u-net
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - cycle2u-net
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    restart: always

networks:
  cycle2u-net:
    driver: bridge
